### PR TITLE
Fix npm install

### PR DESCRIPTION
**Pull request by daun**
**Description**

- Use older/compatible import assertion syntax
- Unpin swup to allow deduplication inside `node_modules`

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [ ] ~~All tests are passing (`npm run test`)~~
- [ ] ~~New or updated tests are included~~
- [ ] ~~The documentation was updated as required~~

**Additional information**

Not sure how to test this, so I guess a blind release.

### CODE REVIEW

**Review by gmrchk — DISMISSED** [review]

**Comment by hirasso** [comment]
The syntax without comma doesn't compile for me. Funny thing: I just tried to reproduce the syntax issue in a reduced test case, and it *compiles in both node v16 as well as v18*!
```js
(async function() {
  const pkg = await loadPluginPackageInfo();
})()

async function loadPluginPackageInfo() {
	const { default: pkg } = await import('../../package.json', { assert: { type: 'json' } });
	return pkg;
}
```
The comma syntax is also the correct one for dynamic imports, if I read this correctly: https://v8.dev/features/import-assertions#dynamic-import()

**Comment by daun** [comment]
@hirasso So the solution would be your example from above? What are you using to compile the example? `tsc` hasn't complained yet.

**Comment by hirasso** [comment]
@daun I'm using esbuild-loader together with webpack 5.

**Comment by daun** [comment]
Just realized: what's important is that it runs on the shell, it doesn't have to compile. I wonder what or who was trying to compile a `bin` script after `npm install`?

**Comment by hirasso** [comment]
> Just realized: what's important is that it runs on the shell, it doesn't have to compile. I wonder what or who was trying to compile a bin script after npm install?

I am getting the error if I run `npm install` on `master` in preload-plugin. That invokes `swup-plugin build` which throws the error. The error only happens when running node 16, v18 works fine. I'm only getting an experimental warning there:

> ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time

**Comment by daun** [comment]
I've updated the fix to use node's filesystem API. Works on node 14, 16, and 18. Let's publish this and see if it solves it.

**Review by hirasso — APPROVED** [review]

**Pull request merged**
